<?php

class Insert_Data_To_Fakes {

	public function up()
	{
        DB::query("insert into fakes (id, type_id, label, value, position, created_at, updated_at, required, button, property, template_id, info, page_id) values (1, 1, 'Upload Fan Gate Image', 'img/fangate_img.jpg', 1, '2013-06-10 12:00:00', '2013-06-10 12:00:00', 1, null, null, 1, 'Use this feature to upload an Fan Gate image. The recommended dimensions of an Image are 809x803 px.', 1);");
        DB::query("insert into fakes (id, type_id, label, value, position, created_at, updated_at, required, button, property, template_id, info, page_id) values (2, 1, 'Header banner', 'img/default_banner.jpg', 1, '2013-06-10 12:00:00', '2013-06-10 12:00:00', 1, null, null, 1, 'Is the main banner on your application. It is usually used to highlight the name of your application or the company name. It is also used to give information about the use of the application or the campaign purpose. The recommended maximum dimension of a header banner is 692x324 px. The recommended photo format is .jpg and .png.', 2);");
        DB::query("insert into fakes (id, type_id, label, value, position, created_at, updated_at, required, button, property, template_id, info, page_id) values (3, 4, 'Info Text', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 2, '2013-06-10 12:00:00', '2013-06-10 12:00:00', 1, null, null, 1, 'Is usually located under the header banner where you describe the use of the application, or give more details about the application.', 2);");
        DB::query("insert into fakes (id, type_id, label, value, position, created_at, updated_at, required, button, property, template_id, info, page_id) values (4, 2, 'Edit main title', 'Personal details', 3, '2013-05-06 13:10:00', '2013-05-06 13:10:00', 1, null, null, 1, 'Use this feature to describe the type of information you are looking for in your application''s entry forms. Example your First Name, Last Name...', 2);");
        DB::query("insert into fakes (id, type_id, label, value, position, created_at, updated_at, required, button, property, template_id, info, page_id) values (5, 6, 'First Name', 'First Name', 4, '2013-05-06 13:10:00', '2013-05-06 13:10:00', 1, null, null, 1, '', 2);");
        DB::query("insert into fakes (id, type_id, label, value, position, created_at, updated_at, required, button, property, template_id, info, page_id) values (6, 6, 'Last Name', 'Last Name', 5, '2013-05-06 13:10:00', '2013-05-06 13:10:00', 1, null, null, 1, '', 2);");
        DB::query("insert into fakes (id, type_id, label, value, position, created_at, updated_at, required, button, property, template_id, info, page_id) values (7, 16, 'Gender', 'Gender', 6, '2013-05-06 13:10:00', '2013-05-06 13:10:00', 1, null, 'Male,Female', 1, '', 2);");
        DB::query("insert into fakes (id, type_id, label, value, position, created_at, updated_at, required, button, property, template_id, info, page_id) values (8, 8, 'Email', 'Email', 7, '2013-05-06 13:10:00', '2013-05-06 13:10:00', 1, null, null, 1, '', 2);");
        DB::query("insert into fakes (id, type_id, label, value, position, created_at, updated_at, required, button, property, template_id, info, page_id) values (9, 8, 'Confirm Email', 'Confirm Email', 8, '2013-05-06 13:10:00', '2013-05-06 13:10:00', 1, null, null, 1, '', 2);");
        DB::query("insert into fakes (id, type_id, label, value, position, created_at, updated_at, required, button, property, template_id, info, page_id) values (10, 10, 'Date of birth', 'Date of birth', 9, '2013-05-06 13:10:00', '2013-05-06 13:10:00', 1, null, null, 1, '', 2);");
        DB::query("insert into fakes (id, type_id, label, value, position, created_at, updated_at, required, button, property, template_id, info, page_id) values (11, 19, 'Accept privacy', 'I have read and accept the Privacy Policy', 10, '2013-05-06 13:10:00', '2013-05-06 13:10:00', 1, null, null, 1, 'Use this feature to edit the text that will be visible for users when they agree to accept the Privacy Policy.', 2);");
        DB::query("insert into fakes (id, type_id, label, value, position, created_at, updated_at, required, button, property, template_id, info, page_id) values (12, 20, 'Accept terms', 'I have read and accept the Terms and Conditions', 11, '2013-05-06 13:10:00', '2013-05-06 13:10:00', 1, null, null, 1, 'Use this feature to edit the text that will be visible for users when they agree to accept the Terms of service.', 2);");
        DB::query("insert into fakes (id, type_id, label, value, position, created_at, updated_at, required, button, property, template_id, info, page_id) values (13, 21, 'Accept rules', 'I have read and agree to the Official Rules', 12, '2013-05-06 13:10:00', '2013-05-06 13:10:00', 1, null, null, 1, 'Use this feature to edit the text that will be visible for users when they agree to accept the competition rules.', 2);");
        DB::query("insert into fakes (id, type_id, label, value, position, created_at, updated_at, required, button, property, template_id, info, page_id) values (14, 18, 'Continue', 'Continue', 13, '2013-06-10 12:00:00', '2013-06-10 12:00:00', 1, null, '#a1bf2e', 1, 'This feature allows users to send you the entered information from the entry form. You can edit the button text by entering the button value or you can edit the button color, by using the color picker.', 2);");
        DB::query("insert into fakes (id, type_id, label, value, position, created_at, updated_at, required, button, property, template_id, info, page_id) values (15, 1, 'Header banner', 'img/default_banner.jpg', 1, '2013-06-10 12:00:00', '2013-06-10 12:00:00', 1, null, null, 1, 'Is the main banner on your application. It is usually used to highlight the name of your application or the company name. It is also used to give information about the use of the application or the campaign purpose. The recommended maximum dimension of a header banner is 692x324 px. The recommended photo format is .jpg and .png.', 3);");
        DB::query("insert into fakes (id, type_id, label, value, position, created_at, updated_at, required, button, property, template_id, info, page_id) values (16, 2, 'Edit main title', 'Main title', 2, '2013-06-10 12:00:00', '2013-06-10 12:00:00', 1, null, null, 1, '', 3);");
        DB::query("insert into fakes (id, type_id, label, value, position, created_at, updated_at, required, button, property, template_id, info, page_id) values (17, 4, 'Info text', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 3, '2013-06-10 12:00:00', '2013-06-10 12:00:00', 1, null, null, 1, '', 3);");

        DB::query("SELECT setval('fakes_id_seq', 17);");
    }

	public function down()
	{
		//
	}

}